<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=windows-1252">
<TITLE>action07 Wash Runs</TITLE>
</HEAD>
<BODY>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=34 >
<TD WIDTH=143  ALIGN=LEFT > <BR></TD><TD WIDTH=433  ALIGN=CENTER  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:20pt FACE="Calibri" COLOR=#7f7f7f>Wash Run</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=96  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>DateTimeCode</FONT></TD>
<TD WIDTH=96  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>20150813110</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=340  ALIGN=LEFT > <BR></TD><TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Batch </FONT></TD>
<TD WIDTH=129  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Batch </FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=23 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=48  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Date</FONT></TD>
<TD WIDTH=87  ALIGN=RIGHT  BGCOLOR=#D8D8D8 ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>8/13/2015</FONT></TD>
<TD WIDTH=69  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Time</FONT></TD>
<TD WIDTH=153  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>number</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#222a35>4</FONT></TD>
<TD WIDTH=105  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Name</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Source </FONT></TD>
<TD WIDTH=230  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Source </FONT></TD>
<TD WIDTH=274  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Source </FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=17 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Product</FONT></TD>
<TD WIDTH=230  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Ingredient</FONT></TD>
<TD WIDTH=274  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Amount</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=72  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Source </FONT></TD>
<TD WIDTH=303  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Source </FONT></TD>
<TD WIDTH=189  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Volume </FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=23 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=72  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Container</FONT></TD>
<TD WIDTH=76  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#222a35>F1</FONT></TD>
<TD WIDTH=120  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Alc/Vol</FONT></TD>
<TD WIDTH=48  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>6.0</FONT></TD>
<TD WIDTH=111  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Volume</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>90.0</FONT></TD>
<TD WIDTH=132  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Remaining</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>0.0</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=56  ALIGN=LEFT > <BR></TD><TD WIDTH=72  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Gallons </FONT></TD>
<TD WIDTH=322  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Collection </FONT></TD>
<TD WIDTH=170  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Starting </FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=23 >
<TD WIDTH=56  ALIGN=LEFT > <BR></TD><TD WIDTH=72  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Distilled</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>15.0</FONT></TD>
<TD WIDTH=104  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>% Proof</FONT></TD>
<TD WIDTH=48  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>76.0</FONT></TD>
<TD WIDTH=120  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Start</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>11:00</FONT></TD>
<TD WIDTH=123  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Proof</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=216  ALIGN=LEFT > <BR></TD><TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Proof </FONT></TD>
<TD WIDTH=130  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Collection </FONT></TD>
<TD WIDTH=200  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Ending </FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=23 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=72  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>temp C</FONT></TD>
<TD WIDTH=169  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Gallons</FONT></TD>
<TD WIDTH=53  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>11.40</FONT></TD>
<TD WIDTH=77  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Stop</FONT></TD>
<TD WIDTH=200  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Proof</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=72  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>pH</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=268  ALIGN=LEFT > <BR></TD><TD WIDTH=80  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Destination </FONT></TD>
<TD WIDTH=117  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>WG </FONT></TD>
<TD WIDTH=136  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>PG </FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=23 >
<TD WIDTH=268  ALIGN=LEFT > <BR></TD><TD WIDTH=80  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>Container</FONT></TD>
<TD WIDTH=46  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>f5</FONT></TD>
<TD WIDTH=91  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>existing</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>0.0</FONT></TD>
<TD WIDTH=98  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>existing</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>0.0</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=412  ALIGN=LEFT > <BR></TD><TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>WG </FONT></TD>
<TD WIDTH=136  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>PG </FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=23 >
<TD WIDTH=412  ALIGN=LEFT > <BR></TD><TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>resulting</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#D8D8D8 ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>15.0</FONT></TD>
<TD WIDTH=97  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>resulting</FONT></TD>
<TD WIDTH=60  ALIGN=RIGHT  BGCOLOR=#D8D8D8 ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>11.4</FONT></TD>
</TR>
</TABLE>
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 >
<TR HEIGHT=19 >
<TD WIDTH=48  ALIGN=LEFT > <BR></TD><TD WIDTH=96  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#7f7f7f>DateTimeCode</FONT></TD>
<TD WIDTH=96  ALIGN=RIGHT  BGCOLOR=#FFFFFF ><FONT style=FONT-SIZE:11pt FACE="Calibri" COLOR=#404040>20150814110</FONT></TD>
</TR>
</TABLE>

<A HREF="#">First</A> <A HREF="#">Previous</A> <A HREF="action07 Wash Runs reportPage2.html">Next</A> <A HREF="action07 Wash Runs reportPage112.html">Last</A></BODY>
</HTML>
